CREATE TABLE `T_TASK_CONFIG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(100) NOT NULL COMMENT '配置类型',
  `CONFIG` mediumtext NOT NULL COMMENT '配置内容',
  `SOURCE` varchar(100) NOT NULL DEFAULT '0' COMMENT '配置来源，如jd-product.xml',
  `STATUS` tinyint(4) DEFAULT '1' COMMENT '状态，0-disable,1-enable',
  `CREATE_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `T_TASK_PRIORITY` (
  `TASK_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BATCH_ID` varchar(100) DEFAULT NULL COMMENT '批次ID',
  `TYPE` varchar(100) NOT NULL COMMENT '类型',
  `URL` varchar(200) DEFAULT NULL COMMENT '链接',
  `PARAMS` varchar(2000) DEFAULT NULL COMMENT '参数',
  `LEVEL` tinyint(4) DEFAULT NULL COMMENT '优先级',
  `STATUS` tinyint(4) DEFAULT NULL COMMENT '状态,0-new,1-cacher,2-ASSIGN,3-DONE,4-error',
  `SOURCE` varchar(200) DEFAULT NULL COMMENT '来源',
  `CREAT_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TASK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `T_TYPE_CONFIG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(100) NOT NULL COMMENT '任务TYPE',
  `TASKER` varchar(200) NOT NULL DEFAULT 'common' COMMENT 'TYPE拥有者，common为针对所有TASKER',
  `MIN_SIZE` int(11) NOT NULL DEFAULT '1' COMMENT '最小值',
  `MAX_SIZE` int(11) NOT NULL DEFAULT '5' COMMENT '最大值',
  `STATUS` smallint(6) NOT NULL DEFAULT '1' COMMENT '状态,0-disable,1-enable',
  `CREATE_TIME` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;