  `ID` bigint(20) NOT NULL auto_increment,
  `SITE_ID` int(11) NOT NULL default '0' COMMENT '站点ID',
  `SHOP_ID` int(11) NOT NULL COMMENT '商店ID',
  `PRODUCT_CODE` varchar(50) default NULL COMMENT '商品编码',
  `PRODUCT_NAME` varchar(1000) NOT NULL COMMENT '商品名称',
  `PRODUCT_URL` varchar(1000) default NULL COMMENT '商品链接',
  `CATEGORY_NAV` varchar(1000) default NULL COMMENT '目录导航',
  `MIN_PRICE` float(12,2) default NULL COMMENT '最低价',
  `MAX_PRICE` float(12,2) default NULL COMMENT '最高价',
  `PRODUCT_PRICE` float(12,2) default NULL COMMENT '当前价',
  `MARKET_PRICE` float(12,2) default NULL COMMENT '市场价',
  `SOLD_NUM` int(11) default NULL COMMENT '销量',
  `COMMENT_NUM` int(11) default NULL COMMENT '评论数',
  `GOOD_COMMENT` int(11) default NULL COMMENT '好评数',
  `POOR_COMMENT` int(11) default NULL COMMENT '差评数',
  `STOCK_NUM` int(11) default NULL COMMENT '创建时间,下架：<0，缺货：0，有货：>0',
  `CREATE_TIME` timestamp NULL default NULL COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL default '0000-00-00 00:00:00' on update CURRENT_TIMESTAMP COMMENT '更新时间',
