  `stat_date` date DEFAULT NULL,
  `brand_name` varchar(150) DEFAULT NULL,
  `sell_date_start` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `category_first_id` int(11) DEFAULT NULL,
  `category_first_name` varchar(150) DEFAULT NULL,
  `category_second_id` int(11) DEFAULT NULL,
  `category_second_name` varchar(150) DEFAULT NULL,
  `category_third_id` int(11) DEFAULT NULL,
  `category_third_name` varchar(150) DEFAULT NULL,
  `goods_code_num` int(11) DEFAULT NULL