DROP TABLES IF EXISTS T_SIMILAR;
CREATE TABLE `T_SIMILAR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SIMILAR_CODE` bigint(20) NOT NULL COMMENT '相似编码,第一批的stamp',
  `SHOP_ID` int NOT NULL COMMENT '商店ID',
  `PRODUCT_CODE` varchar(50)  COMMENT '商品编号',
  `PRODUCT_NAME` varchar(1000) COMMENT '商品名称',
  `PRODUCT_URL` varchar(1000) COMMENT '商品链接',
  `PRODUCT_PRICE` float(12,2) COMMENT '当前价',
  `BAR_CODE` varchar(13)  COMMENT '商品条码',
  `IMG_URL` varchar(1000) COMMENT '图片路径',
  `SOURCE` varchar(100) COMMENT '来源，JSON存多个来源',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_SIMILAR_PRODUCT_CODE` (`PRODUCT_CODE`),
  KEY `IDX_T_SIMILAR_SIMILAR_CODE` (`SIMILAR_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '相似商品表';