DROP TABLES IF EXISTS T_BARCODE_ITEM;
CREATE TABLE `T_BARCODE_ITEM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BAR_CODE` varchar(13) NOT NULL COMMENT '商品条码',
  `PRODUCT_NAME` varchar(1000) NOT NULL COMMENT '商品名称',
  `PRODUCT_URL` varchar(1000) COMMENT '商品链接',
  `PRODUCT_BRAND` varchar(200)  COMMENT '品牌名称',
  `PRODUCT_MODEL` varchar(200)  COMMENT '型号',
  `PRODUCT_ATTR` varchar(2000) COMMENT '商品属性',
  `IMG_URL` varchar(2000) COMMENT '图片路径',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '条码商品表';
ALTER TABLE `T_BARCODE_ITEM` 
ADD INDEX INDEX_T_BARCODE_ITEM_BAR_CODE (`BAR_CODE`);

DROP TABLES IF EXISTS T_SHOP;
CREATE TABLE `T_SHOP` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT,
  `SITE_CODE`  varchar(20) COMMENT '站点域名',
  `SHOP_NAME` varchar(200) NOT NULL COMMENT '店铺名称',
  `SHOP_CODE` varchar(20) COMMENT '店铺编码',
  `SHOP_URL` varchar(1000)  COMMENT '店铺地址',
  `ON_LINE` tinyint DEFAULT '0'  COMMENT '线上店铺，0-否，1-是',
  `IS_SELF` tinyint DEFAULT '0'  COMMENT '自营店，0-否，1-是',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_SHOP_SHOP_NAME` (`SHOP_NAME`),
  KEY `IDX_T_SHOP_SITE_CODE` (`SITE_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8 COMMENT '店铺信息表';


DROP TABLES IF EXISTS T_PRODUCT;
CREATE TABLE `T_PRODUCT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SHOP_ID` int NOT NULL COMMENT '商店ID',
  `PRODUCT_CODE` varchar(50)  NOT NULL COMMENT '商品编号',
  `PRODUCT_NAME` varchar(1000) NOT NULL COMMENT '商品名称',
  `MARKET_PRICE` float(12,2) COMMENT '市场价',
  `PRODUCT_URL` varchar(1000) COMMENT '商品链接',
  `PRODUCT_BRAND` varchar(200)  COMMENT '品牌名称',
  `PRODUCT_MODEL` varchar(200)  COMMENT '型号',
  `PRODUCT_ATTR` varchar(2000) COMMENT '商品属性',
  `BAR_CODE` varchar(13)  COMMENT '商品条码',
  `IMG_URL` varchar(2000) COMMENT '图片路径',
  `ONSAIL_TIME` timestamp  NULL  COMMENT '上架时间',
  `CREATE_TIME` timestamp  NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_PRODUCT_CODE` (`PRODUCT_CODE`,`SHOP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '产品表';


DROP TABLES IF EXISTS T_PRODUCT_STAT;
CREATE TABLE `T_PRODUCT_STAT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SHOP_ID` int NOT NULL COMMENT '商店ID',
  `PRODUCT_CODE` varchar(50)  COMMENT '商品编码',
  `PRODUCT_NAME` varchar(1000) NOT NULL COMMENT '商品名称',
  `PRODUCT_URL` varchar(1000) COMMENT '商品链接',
  `PRODUCT_PRICE` float(12,2) COMMENT '当前价',
  `MARKET_PRICE` float(12,2) COMMENT '市场价',
  `SOLD_NUM` int COMMENT '销量',
  `COMMENT_NUM` int COMMENT '评论数',
  `STOCK_NUM` int COMMENT '创建时间,下架：<0，缺货：0，有货：>0',
  `CREATE_TIME` timestamp  NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_PRODUCT_STAT_CODE_SHOP_ID` (`PRODUCT_CODE`,`SHOP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '产品状态表';

DROP TABLES IF EXISTS T_PRODUCT_STAT_HIS;
CREATE TABLE `T_PRODUCT_STAT_HIS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SHOP_ID` int NOT NULL COMMENT '商店ID',
  `PRODUCT_CODE` varchar(50)  COMMENT '商品编码',
  `PRODUCT_NAME` varchar(1000) NOT NULL COMMENT '商品名称',
  `PRODUCT_URL` varchar(1000) COMMENT '商品链接',
  `PRODUCT_PRICE` float(12,2) COMMENT '当前价',
  `MARKET_PRICE` float(12,2) COMMENT '市场价',
  `SOLD_NUM` int COMMENT '销量',
  `COMMENT_NUM` int COMMENT '评论数',
  `STOCK_NUM` int COMMENT '创建时间,下架：<0，缺货：0，有货：>0',
  `CREATE_TIME` timestamp  NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_PRODUCT_STAT_HIS_CODE_SHOP_ID` (`PRODUCT_CODE`,`SHOP_ID`),
  KEY `IDX_T_PRODUCT_STAT_HIS_CREATE_TIME` (`CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '产品状态历史表';
