ALTER TABLE T_PRODUCT_STAT
ADD COLUMN `SITE_ID` int NOT NULL DEFAULT '0' COMMENT '站点ID'  AFTER `ID`,
ADD COLUMN `POOR_COMMENT` int COMMENT '差评数' AFTER `COMMENT_NUM`,
ADD COLUMN `GOOD_COMMENT` int COMMENT '好评数' AFTER `COMMENT_NUM`;

ALTER TABLE T_PRODUCT_STAT_HIS
ADD COLUMN `SITE_ID` int NOT NULL DEFAULT '0' COMMENT '站点ID'  AFTER `ID`,
ADD COLUMN `POOR_COMMENT` int COMMENT '差评数' AFTER `COMMENT_NUM`,
ADD COLUMN `GOOD_COMMENT` int COMMENT '好评数' AFTER `COMMENT_NUM`;

ALTER TABLE T_PRODUCT
ADD COLUMN `SITE_ID` int NOT NULL DEFAULT '0' COMMENT '站点ID'  AFTER `ID`;

ALTER TABLE T_SHOP
ADD COLUMN `PARENT_ID` int COMMENT '父店铺'  AFTER `ID`;

ALTER TABLE T_SIMILAR CHANGE SHOP_ID SITE_ID INT;

ALTER TABLE T_PRODUCT
ADD COLUMN `UNION_URL`  varchar(1000) COMMENT '推广URL' AFTER `IMG_URL`;
ALTER TABLE T_PRODUCT
ADD COLUMN `CATEGORY_NAV` varchar(1000) COMMENT '类目导航';

