DROP TABLES IF EXISTS T_CRAWLER_WARN_HIS;
CREATE TABLE `T_CRAWLER_WARN_HIS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(50) NOT NULL COMMENT '任务类型',
  `CLIEN_NAME` varchar(50) NOT NULL COMMENT '客户端名称',
  `TASK_ID` bigint(20) NOT NULL default '0'  COMMENT '任务ID',
  `PROCESS_ID` varchar(50) NOT NULL default '0'  COMMENT '任务ID',
  `PARAM` varchar(2000) NOT NULL default '0' COMMENT '任务参数',
  `RETRY` int NOT NULL default '0' COMMENT '重试次数',
  `MESSAGE` text COMMENT '异常信息',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_CRAWLER_WARN_HIS_CLIEN_NAME` (`CLIEN_NAME`),
  KEY `IDX_T_CRAWLER_WARN_HIS_TYPE` (`TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '会话历史表';