DROP TABLES IF EXISTS T_CLIENT_TOKEN;
CREATE TABLE `T_CLIENT_TOKEN` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CLIENT_TYPE` varchar(50) NOT NULL COMMENT '客户端类型',
  `CLIENT_ID` varchar(15) NOT NULL default '' COMMENT '客户端ID',
  `CLIENT_SECRET` varchar(20) NOT NULL default '' COMMENT '客户端密钥',
  `CLIENT_PARAMS` varchar(200) NOT NULL default '' COMMENT '其他参数',
  `REFRESH_TOKEN` varchar(100) NOT NULL default '' COMMENT '刷新的TOKEN',
  `ACCESS_TOKEN` varchar(100) NOT NULL default '' COMMENT '使用的TOKEN',
  `NEXT_REFRESH_TIME` datetime NULL  COMMENT '下次刷新时间',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_CLIENT_TOKEN_CLIENT_TYPE_ID` (`CLIENT_TYPE`,`CLIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '客户端授权表';