ALTER TABLE T_PRODUCT_STAT
ADD COLUMN `SITE_ID` int NOT NULL DEFAULT '0' COMMENT '站点ID'  AFTER `ID`,
ADD COLUMN `POOR_COMMENT` int COMMENT '差评数' AFTER `COMMENT_NUM`,
ADD COLUMN `GOOD_COMMENT` int COMMENT '好评数' AFTER `COMMENT_NUM`;

ALTER TABLE T_PRODUCT_STAT_HIS
ADD COLUMN `SITE_ID` int NOT NULL DEFAULT '0' COMMENT '站点ID'  AFTER `ID`,
ADD COLUMN `POOR_COMMENT` int COMMENT '差评数' AFTER `COMMENT_NUM`,
ADD COLUMN `GOOD_COMMENT` int COMMENT '好评数' AFTER `COMMENT_NUM`;

ALTER TABLE T_PRODUCT
ADD COLUMN `SITE_ID` int NOT NULL DEFAULT '0' COMMENT '站点ID'  AFTER `ID`;

ALTER TABLE T_SHOP
ADD COLUMN `PARENT_ID` int COMMENT '父店铺'  AFTER `ID`;

DROP TABLES IF EXISTS T_PRODUCT_SUMMARY;
CREATE TABLE `T_PRODUCT_SUMMARY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SITE_ID` varchar(50) COMMENT '站点ID',
  `SHOP_ID` varchar(50) COMMENT '店铺ID',
  `PRODUCT_CODE` varchar(50)  COMMENT '商品编码',
  `IS_PROMOTE` tinyint NOT NULL default '0' COMMENT '促销，0-FALSE,1-TRUE',
  `PRICE_RISE` float(12,2) COMMENT '价格增长率 ',
  `SALE_NUM_RISE` float(12,2) COMMENT '销量增长率',
  `COMMENT_NUM_RISE` float(12,2) COMMENT '评论增长率',
  `GOOD_COMMENT_RISE` float(12,2) COMMENT '好评增长率',
  `POOR_COMMENT_RISE` float(12,2) COMMENT '差评增长率',
  `IS_DELETE`  tinyint NOT NULL default '0' COMMENT '删除，0-FALSE,1-TRUE',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_PRODUCT_SUMMARY_CODE_SITE` (`SITE_ID`,`PRODUCT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '促销产品映射表';

DROP TABLES IF EXISTS T_PRODUCT_TRUST;
CREATE TABLE `T_PRODUCT_TRUST` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SITE_ID` varchar(50) COMMENT '站点ID',
  `PRODUCT_CODE` varchar(50)  COMMENT '商品编码',
  `IS_PROMOTE_FAKE` tinyint NOT NULL default '0' COMMENT '假促销，0-FALSE,1-TRUE',
  `IS_DELETE` tinyint NOT NULL default '0' COMMENT '0-未删除,1-删除',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_PRODUCT_SUMMARY_CODE_SITE` (`SITE_ID`,`PRODUCT_CODE`),
  KEY `IDX_T_PRODUCT_SUMMARY_MCODE_SITE` (`SITE_ID`,`PROMOTE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '促销产品映射表';

