DROP TABLES IF EXISTS T_SESSION_DAILY;
CREATE TABLE `T_SESSION_DAILY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CLIEN_NAME` varchar(50) NOT NULL COMMENT '客户端名称',
  `REQUEST_SIZE` int NOT NULL default '0'  COMMENT '请求数',
  `RESPONE_SIZE` int NOT NULL default '0' COMMENT '响应数',
  `ERROR_SIZE` int NOT NULL default '0' COMMENT '异常数',
  `SUCCESS_NUM` int NOT NULL default '0' COMMENT '成功数',
  `FAIL_NUM` int NOT NULL default '0' COMMENT '失败数',
  `WORK_TIME` int NOT NULL default '0' COMMENT '工作时长',
  `SETUP_TIMES` int NOT NULL default '0' COMMENT '启动次数',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_SESSION_DAILY_CREATE_TIME` (`CREATE_TIME`),
  KEY `IDX_T_SESSION_DAILY_CLIEN_NAME` (`CLIEN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '会话每日汇总表';


ALTER TABLE T_PRODUCT_STAT_HIS
ADD COLUMN `CATEGORY_NAV` varchar(1000) COMMENT '目录导航' AFTER `PRODUCT_URL`;

ALTER TABLE T_PRODUCT_STAT
ADD COLUMN `CATEGORY_NAV` varchar(1000) COMMENT '目录导航' AFTER `PRODUCT_URL`;

ALTER TABLE `T_PRODUCT_STAT`
ADD INDEX IDX_T_PRODUCT_STAT_CATEGORY_NAV ( `CATEGORY_NAV`(50) ) ;

DROP TABLES IF EXISTS T_SEARCH_RANK_HIS;
CREATE TABLE `T_SEARCH_RANK_HIS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEARCH_WORD` varchar(200) NOT NULL COMMENT '关键词',
  `SEARCH_URL` varchar(1000)  COMMENT '排行链接',
  `SHOP_ID` int NOT NULL COMMENT '商店ID',
  `PRODUCT_CODE` varchar(50)  NOT NULL COMMENT '商品编号',
  `PRODUCT_NAME` varchar(1000) NOT NULL COMMENT '商品名称',
  `PRODUCT_PRICE` float(12,2) COMMENT '市场价',
  `PRODUCT_URL` varchar(1000) COMMENT '商品链接',
  `SORT_TYPE` tinyint NOT NULL DEfault '0' COMMENT '排序类型',
  `SORT_RANK` int  NOT NULL DEfault '0' COMMENT '商品链接',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_SEARCH_RANK_HIS_CREATE_TIME` (`CREATE_TIME`),
  KEY `IDX_T_SEARCH_RANK_HIS_CLIEN_NAME` (`CLIEN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '会话每日汇总表';