DROP TABLES IF EXISTS T_SESSION_HIS;
CREATE TABLE `T_SESSION_HIS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SESSION_ID` varchar(36) NOT NULL COMMENT '会话ID',
  `CLIEN_NAME` varchar(50) NOT NULL COMMENT '客户端名称',
  `REQUEST_SIZE` int NOT NULL default '0'  COMMENT '请求数',
  `RESPONE_SIZE` int NOT NULL default '0' COMMENT '响应数',
  `ERROR_SIZE` int NOT NULL default '0' COMMENT '异常数',
  `SUCCESS_NUM` int NOT NULL default '0' COMMENT '成功数',
  `FAIL_NUM` int NOT NULL default '0' COMMENT '失败数',
  `STATUS` tinyint NOT NULL default '1' COMMENT '状态，0-下线，1-上线',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_SESSION_HIS_SESSION_ID` (`SESSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '会话历史表';

ALTER TABLE `T_TASK_PRIORITY`
ADD INDEX IDX_T_TASK_PRIORITY_TYPE ( `TYPE` );

ALTER TABLE T_PRODUCT_STAT_HIS
ADD COLUMN `MAX_PRICE` float(12,2) COMMENT '最高价' AFTER `PRODUCT_URL`,
ADD COLUMN `MIN_PRICE` float(12,2) COMMENT '最低价' AFTER `PRODUCT_URL` ;

ALTER TABLE `T_PRODUCT_STAT_HIS`
ADD INDEX IDX_T_PRODUCT_STAT_HIS_CODE ( `PRODUCT_CODE` ),
ADD INDEX IDX_T_PRODUCT_STAT_HIS_CREATE_TIME ( `CREATE_TIME` ) ;

ALTER TABLE `T_PRODUCT_STAT`
ADD INDEX IDX_T_PRODUCT_STAT_UPDATE_TIME ( `UPDATE_TIME` ) ;