DROP TABLES IF EXISTS T_CRAWLER_WARN_HIS;
CREATE TABLE `T_CRAWLER_WARN_HIS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(50) NOT NULL COMMENT '任务类型',
  `CLIENT_NAME` varchar(15) NOT NULL default '0' COMMENT '客户端名称',
  `MAC_ADDR` varchar(12) NOT NULL  default '0' COMMENT 'MAC地址',
  `TASK_ID` bigint(20) NOT NULL default '0'  COMMENT '任务ID',
  `PROCESS_ID` varchar(50) NOT NULL default '0'  COMMENT '进度ID',
  `PARAM` varchar(2000) NOT NULL default '0' COMMENT '任务参数',
  `RETRY` int NOT NULL default '0' COMMENT '重试次数',
  `MESSAGE` text COMMENT '异常信息',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_CRAWLER_WARN_HIS_CLIENT_NAME` (`CLIENT_NAME`),
  KEY `IDX_T_CRAWLER_WARN_HIS_TYPE` (`TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '抓取异常历史表';

DROP TABLES IF EXISTS T_PROMOTION_TRACK;
CREATE TABLE `T_PROMOTION_TRACK` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SITE_ID` int NOT NULL DEFAULT '0' COMMENT '站点ID',
  `PRODUCT_CODE` varchar(50)  COMMENT '商品编码',
  `PRODUCT_NAME` varchar(1000) NOT NULL COMMENT '商品名称',
  `PRODUCT_URL` varchar(1000) COMMENT '商品链接',
  `FROM_PRICE` float(12,2) COMMENT '当前价',
  `TARGET_PRICE` float(12,2) COMMENT '目标促销价',
  `TO_PRICE` float(12,2) COMMENT '最终促销价',
  `PROMOTION_DETAIL` varchar(1000) NOT NULL COMMENT '促销信息',
  `FROM_TIME` timestamp NULL  COMMENT '创建时间',
  `TO_TIME` timestamp NULL  COMMENT '创建时间',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_PROMOTION_TRACK_SITE_CODE` (`SITE_ID`,`PRODUCT_CODE`),
  KEY `IDX_T_PROMOTION_TRACK_FROM_TIME` (`FROM_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '诚信促销跟踪';


DROP TABLES IF EXISTS T_BRAND_STORE;
CREATE TABLE `T_BRAND_STORE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SITE_ID` int NOT NULL DEFAULT '0' COMMENT '站点ID',
  `BRAND_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '品牌编码',
  `BRAND_NAME` varchar(50) NOT NULL DEFAULT '' COMMENT '品牌名称',
  `BRAND_URL` varchar(1000) COMMENT '品牌链接',
  `SYNONYM` varchar(1000) COMMENT '同义词',
  `REGION` varchar(50) COMMENT '地区',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_BRAND_STORE_SITE_CODE` (`SITE_ID`,`BRAND_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '品牌库';

DROP TABLES IF EXISTS T_BRAND_SHOP;
CREATE TABLE `T_BRAND_SHOP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SITE_ID` int NOT NULL DEFAULT '0' COMMENT '站点ID',
  `BRAND_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '品牌ID',
  `BRAND_NAME` varchar(50) NOT NULL DEFAULT '' COMMENT '品牌名称',
  `SHOP_NAME` varchar(50) NOT NULL DEFAULT '' COMMENT '店铺名称',
  `SHOP_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '店铺编码',
  `SHOP_URL` varchar(1000) COMMENT '店铺链接',
  `SHOP_TYPE` tinyint NOT NULL default '3' COMMENT '0-旗舰店，1-专卖店，2-专营店，3-其他',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_BRAND_SHOP_NAME` (`SHOP_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '品牌店铺表';