DROP TABLES IF EXISTS T_BARCODE_ITEM;
CREATE TABLE `T_BARCODE_ITEM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SHOP_CODE` varchar(100) NOT NULL COMMENT '商店ID',
  `BAR_CODE` varchar(200) NOT NULL COMMENT '商品条码',
  `PRODUCT_NAME` varchar(1000) NOT NULL COMMENT '商品名称',
  `PRODUCT_URL` varchar(1000) COMMENT '商品链接',
  `PRODUCT_BRAND` varchar(200)  COMMENT '品牌名称',
  `PRODUCT_MODEL` varchar(200)  COMMENT '型号',
  `PRODUCT_ATTR` varchar(2000) COMMENT '商品属性',
  `IMG_URL` varchar(2000) COMMENT '图片路径',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '条码商品表';
ALTER TABLE `T_BARCODE_ITEM` 
ADD INDEX INDEX_T_BARCODE_ITEM_BAR_CODE (`BAR_CODE`);

DROP TABLES IF EXISTS T_SHOP_INFO;
CREATE TABLE `T_SHOP_INFO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SHOP_NAME` varchar(200) NOT NULL COMMENT '店铺名称',
  `SHOP_CODE` varchar(100) NOT NULL COMMENT '店铺编码',
  `SHOP_URL` varchar(1000)  COMMENT '店铺地址',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_SHOP_INFO_SHOP_NAME` (`SHOP_NAME`),
  KEY `IDX_T_SHOP_INFO_SHOP_CODE` (`SHOP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '店铺信息表';
