DROP TABLES IF EXISTS T_MESSAGE;
CREATE TABLE `T_MESSAGE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(50) COMMENT '消息类型',
  `MESSAGE` varchar(1000)  COMMENT '消息内容',
  `SOURCE` varchar(50) COMMENT '消息来源',
  `HANDLER` varchar(100) COMMENT '处理者',
  `STATUS` tinyint NOT NULL DEfault '0' COMMENT '状态',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_MESSAGE_TYPE` (`TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '消息记录表';