DROP TABLES IF EXISTS T_SESSION_DAILY;
CREATE TABLE `T_SESSION_DAILY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CLIEN_NAME` varchar(50) NOT NULL COMMENT '客户端名称',
  `REQUEST_SIZE` int NOT NULL default '0'  COMMENT '请求数',
  `RESPONE_SIZE` int NOT NULL default '0' COMMENT '响应数',
  `ERROR_SIZE` int NOT NULL default '0' COMMENT '异常数',
  `SUCCESS_NUM` int NOT NULL default '0' COMMENT '成功数',
  `FAIL_NUM` int NOT NULL default '0' COMMENT '失败数',
  `WORK_TIME` int NOT NULL default '0' COMMENT '工作时长',
  `SETUP_TIMES` int NOT NULL default '0' COMMENT '启动次数',
  `CREATE_TIME` timestamp NULL  COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_T_SESSION_DAILY_CREATE_TIME` (`CREATE_TIME`),
  KEY `IDX_T_SESSION_DAILY_CLIEN_NAME` (`CLIEN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '会话每日汇总表';


ALTER TABLE T_PRODUCT_STAT_HIS
ADD COLUMN `CATEGORY_NAV` varchar(1000) COMMENT '目录导航' AFTER `PRODUCT_URL`;

ALTER TABLE T_PRODUCT_STAT
ADD COLUMN `CATEGORY_NAV` varchar(1000) COMMENT '目录导航' AFTER `PRODUCT_URL`;

ALTER TABLE `T_PRODUCT_STAT`
ADD INDEX IDX_T_PRODUCT_STAT_CATEGORY_NAV ( `CATEGORY_NAV`(50) ) ;
