CREATE TABLE T_MAKER_TASK_TRACK
(
	  TASK_ID BIGINT NOT NULL,
	  TASK_URL VARCHAR(1000),
	  TASK_CODE INTEGER,
	  TASK_TYPE VARCHAR(20),
	  TASK_LEVEL SMALLINT,
	  TASK_RETRIES SMALLINT,
	  TASK_STATUS SMALLINT,
	  RESULT_STATUS SMALLINT,
	  TASK_SERIES VARCHAR(20),
	  TRACK_PARAM VARCHAR(1000),
	  CLIENT_ID VARCHAR(100),
	  CREATE_TIME TIMESTAMP,
	  UPDATE_TIME TIMESTAMP,
	  PRIMARY KEY (TASK_ID)
)
CREATE INDEX INDEX_MAKER_TASK_TRACK_CODE ON T_MAKER_TASK_TRACK(TASK_CODE)
CREATE INDEX INDEX_MAKER_TASK_TRACK_TYPE ON T_MAKER_TASK_TRACK(TASK_TYPE)

