DROP TABLE IF EXISTS T_TASK;
CREATE TABLE T_TASK(
  ID INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  TASK_TYPE VARCHAR(60) NOT NULL COMMENT '类型',
  TASK_CODE INT(11) COMMENT 'URL-hasCode',
  TASK_URL VARCHAR(1000)  COMMENT 'URL',
  TASK_PARAM VARCHAR(1000) COMMENT '参数',
  TASK_LEVEL INT(4)  COMMENT '优先级',
  TASK_SERIES VARCHAR(20)  COMMENT '系列',
  CREATE_TIME TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '任务表';
ALTER TABLE T_TASK ADD INDEX INDEX_TASK_TYPE(TASK_TYPE);
ALTER TABLE T_TASK ADD INDEX INDEX_TASK_CODE(TASK_CODE);

DROP TABLE IF EXISTS T_TASK_TRACK;
CREATE TABLE T_TASK_TRACK(
  ID INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  TASK_ID INT(11) NOT NULL  COMMENT '任务编号',
  TASK_URL VARCHAR(1000)  COMMENT 'URL',
  TASK_CODE INT(11) COMMENT 'URL-hasCode',
  TASK_TYPE VARCHAR(120) NOT NULL COMMENT '任务类型',
  TASK_LEVEL INT(4)  COMMENT '任务优先级',
  TASK_RETRIES INT(4) DEFAULT '0' COMMENT '重试次数',
  TASK_STATUS INT(4)  NULL COMMENT '任务状态,1-创建，2-激活，3-分配，4-执行，5-提交，6-处理',
  RESULT_STATUS INT(4)  NULL COMMENT '结果状态,1-成功，2-失败，3-堵塞',
  TASK_SERIES VARCHAR(20) DEFAULT NULL COMMENT '系列',
  TRACK_PARAM VARCHAR(1000) COMMENT '跟踪参数',
  CLIENT_ID VARCHAR(100) COMMENT 'Client,编号',
  CREATE_TIME DATETIME COMMENT '创建时间',
  UPDATE_TIME TIMESTAMP COMMENT '更新时间,ACTIVE-PUSH-ASSIGN-EXECUTE-COMMIT-DONE',
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '任务跟踪表';
ALTER TABLE T_TASK_TRACK ADD INDEX INDEX_TASK_TRACK_ID (TASK_ID);
ALTER TABLE T_TASK_TRACK ADD INDEX INDEX_TASK_TRACK_SERIES (TASK_SERIES);
