CREATE TABLE T_GERENT_TASK
( 
  ID BIGINT NOT NULL GENERATED AlWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TASK_ID BIGINT NOT NULL,
  TASK_URL VARCHAR(1000),
  TASK_TYPE VARCHAR(120) NOT NULL,
  TASK_LEVEL INTEGER  NOT NULL,
  TASK_PARAM VARCHAR(1000),
  PRIMARY KEY (ID)
)

CREATE INDEX INDEX_GERENT_TASK_ID ON T_GERENT_TASK(TASK_ID)
CREATE INDEX INDEX_GERENT_TASK_TYPE ON T_GERENT_TASK(TASK_TYPE)

CREATE TABLE T_GERENT_TYPE
(     
      ID BIGINT NOT NULL GENERATED AlWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	  TYPE_NAME VARCHAR(60),
	  GERENT_LIMIT INTEGER,
	  MAKER_LIMIT INTEGER,
	  TRIGGER_LIMIT INTEGER,
	  TYPE_STATUS SMALLINT,
	  MAKER_URL VARCHAR(200),
	  CREATE_TIME TIMESTAMP,
	  UPDATE_TIME TIMESTAMP,
	  PRIMARY KEY (ID)
)
CREATE INDEX INDEX_GERENT_TYPE_NAME ON T_GERENT_TYPE(TYPE_NAME)


CREATE TABLE T_GERENT_CLIENT
(     
      ID BIGINT NOT NULL GENERATED AlWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	  CLIENT_NAME VARCHAR(20),
	  CLIENT_PARAM VARCHAR(600),
	  WORK_PARAM VARCHAR(1000),
	  CLIENT_STATUS SMALLINT,
	  CREATE_TIME TIMESTAMP,
	  LOGIN_TIME TIMESTAMP,
	  UPDATE_TIME TIMESTAMP,
	  PRIMARY KEY (ID)
)
CREATE INDEX T_GERENT_CLIENT_NAME ON T_GERENT_CLIENT(CLIENT_NAME)