window.location.href = 'http://login.etao.com/?spm=0.0.0.0.NTyQZP&redirect_url=http%3A%2F%2Fjf.etao.com%2F%3F';
document.referer = 'http://jf.etao.com/?';
ilog('start.........');

//var json_ua = null,form_tk = (document.getElementsByName('rds_form_token')[0] && document.getElementsByName('rds_form_token')[0].value) || '';
//var UA_Opt = new Object;
//UA_Opt.ExTarget = ['password','password_input'];
//UA_Opt.FormId = "login";
//UA_Opt.GetAttrs = ['href', 'src'];
//UA_Opt.Token = form_tk;
//UA_Opt.LogVal = "json_ua";
//UA_Opt.MaxMCLog = 100;
//UA_Opt.MaxKSLog = 100;
//UA_Opt.MaxMPLog = 100;
//UA_Opt.MaxFocusLog = 100;
//UA_Opt.SendMethod = 9;
//UA_Opt.Flag = 32766;

//var ua = "";
//var UA_Opt = new Object();
//UA_Opt.LogVal = "ua";
//UA_Opt.MaxMCLog=3;
//UA_Opt.MaxMPLog=3;
//UA_Opt.MaxKSLog=3;
//UA_Opt.Token=new Date().getTime()+":"+Math.random();
//UA_Opt.SendMethod=8;
//UA_Opt.Flag=14222;

var UA_Opt = new Object;
UA_Opt.ExTarget = [ 'TPL_password_1','J_Pwd1','J_PwdV'];
UA_Opt.ResHost = 'acjstb.aliyun.com';
UA_Opt.FormId = "J_StaticForm";
UA_Opt.LogVal = "log"; 
UA_Opt.Token = new Date().getTime()+":"+Math.random();  
UA_Opt.ImgUrl = "";  
UA_Opt.GetAttrs = ['href', 'src']; 
UA_Opt.MaxMCLog = 150;  
UA_Opt.MaxKSLog = 150;  
UA_Opt.MaxMPLog = 150;  
UA_Opt.MPInterval = 150;  
UA_Opt.SendInterval = 10;  
UA_Opt.SendMethod = 1;
UA_Opt.Flag = 131071;
