//UA_InputId
var staticFormEle = document['createElement']("form");
staticFormEle['action'] = 'https://login.taobao.com/member/login.jhtml';
staticFormEle['method'] = 'post';
staticFormEle['id'] = 'J_StaticForm';
var userEle = document['createElement']("input");
userEle['type'] = 'text';
userEle['name'] = 'TPL_username';
userEle['id'] = 'TPL_username_1';
userEle['class'] = 'login-text J_UserName';
userEle['value'] = '';
userEle['maxlength'] = '32';
userEle['tabindex'] = '1';
var phEle = document['createElement']("span");
phEle['class'] = "ph-label";
staticFormEle.appendChild(phEle);
staticFormEle.appendChild(userEle);
document.body.appendChild(staticFormEle);
// UA_Opt['reload'] = hrt;
window.UA_Opt.reload();
var event = document.createEvent('HTMLEvents');
event.initEvent("mousedown", true, true);
event.target = phEle;
event.altKey = false;
event.bubbles = true;
event.button = 0;
event.charCode = 0;
event.clientX = 87;
event.clientY = 86;
event.clipboardData = undefined;
event.ctrlKey = false;
event.currentTarget = document;
event.dataTransfer = null;
event.defaultPrevented = false;
event.detail = 1;
event.eventPhase = 3;
event.fromElement = null;
event.keyCode = 0;
event.layerX = 41;
event.layerY = 13;
event.metaKey = false;
event.offsetX = 41;
event.offsetY = 13;
event.pageX = 87;
event.pageY = 86;
event.relatedTarget = null;
event.returnValue = true;
event.screenX = 876;
event.screenY = 290;
event.shiftKey = false;
event.webkitMovementX = 0;
event.webkitMovementY = 0;
event.which = 1;
event.x = 87;
event.y = 86
document.dispatchEvent(event);

var event = document.createEvent('HTMLEvents');
event.initEvent("keydown", true, true);
event.target = userEle;
altGraphKey = false;
event.altKey = false;
event.bubbles = true;
event.cancelBubble = false;
event.cancelable = true;
event.charCode = 0;
event.clipboardData = undefined;
event.ctrlKey = false;
event.currentTarget = document;
event.defaultPrevented = false;
event.detail = 0;
event.eventPhase = 3;
event.keyIdentifier = "U+0036";
event.keyLocation = 0;
event.layerX = 0;
event.layerY = 0;
event.location = 0;
event.metaKey = false;
event.pageX = 0;
event.pageY = 0;
event.repeat = false;
event.returnValue = true;
event.shiftKey = false;
var uname = 'lcstore99';
for (var i = 0; i < uname.length; i++) {
	var keyCode = uname.charCodeAt(i);
	if (keyCode >= 48 && keyCode <= 57) {
	} else {
		keyCode = keyCode - 32;
	}
	event.keyCode = keyCode;
	event.which = keyCode;
	document.dispatchEvent(event);
}

var event = document.createEvent('HTMLEvents');
event.initEvent("keydown", true, true);
event.target = userEle;
altGraphKey = false;
event.altKey = false;
event.bubbles = true;
event.cancelBubble = false;
event.cancelable = true;
event.charCode = 0;
event.clipboardData = undefined;
event.ctrlKey = false;
event.currentTarget = document;
event.defaultPrevented = false;
event.detail = 0;
event.eventPhase = 3;
event.keyIdentifier = "U+0036";
event.keyLocation = 0;
event.layerX = 0;
event.layerY = 0;
event.location = 0;
event.metaKey = false;
event.pageX = 0;
event.pageY = 0;
event.repeat = false;
event.returnValue = true;
event.shiftKey = false;
var newUa = eval(UA_Opt.LogVal);
ilog('@@@@[' + UA_Opt.LogVal + ']=' + newUa);
